[2022-04-13 06:12:42,067] {processor.py:163} INFO - Started process (PID=87) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:12:42,070] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:12:42,071] {logging_mixin.py:109} INFO - [2022-04-13 06:12:42,071] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:12:42,077] {logging_mixin.py:109} INFO - [2022-04-13 06:12:42,074] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:12:42,109] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:12:42,133] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.096 seconds
[2022-04-13 06:13:12,237] {processor.py:163} INFO - Started process (PID=116) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:13:12,239] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:13:12,240] {logging_mixin.py:109} INFO - [2022-04-13 06:13:12,240] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:13:12,244] {logging_mixin.py:109} INFO - [2022-04-13 06:13:12,242] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:13:12,268] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:13:12,282] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.050 seconds
[2022-04-13 06:13:42,352] {processor.py:163} INFO - Started process (PID=136) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:13:42,369] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:13:42,370] {logging_mixin.py:109} INFO - [2022-04-13 06:13:42,370] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:13:42,373] {logging_mixin.py:109} INFO - [2022-04-13 06:13:42,372] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:13:42,393] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:13:42,402] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.054 seconds
[2022-04-13 06:14:12,474] {processor.py:163} INFO - Started process (PID=158) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:14:12,475] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:14:12,476] {logging_mixin.py:109} INFO - [2022-04-13 06:14:12,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:14:12,480] {logging_mixin.py:109} INFO - [2022-04-13 06:14:12,478] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:14:12,502] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:14:12,512] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
[2022-04-13 06:14:42,588] {processor.py:163} INFO - Started process (PID=189) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:14:42,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:14:42,620] {logging_mixin.py:109} INFO - [2022-04-13 06:14:42,620] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:14:42,623] {logging_mixin.py:109} INFO - [2022-04-13 06:14:42,622] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:14:42,647] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:14:42,657] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.074 seconds
[2022-04-13 06:15:12,728] {processor.py:163} INFO - Started process (PID=211) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:15:12,730] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:15:12,731] {logging_mixin.py:109} INFO - [2022-04-13 06:15:12,731] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:15:12,734] {logging_mixin.py:109} INFO - [2022-04-13 06:15:12,733] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:15:12,759] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:15:12,772] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.048 seconds
[2022-04-13 06:15:42,846] {processor.py:163} INFO - Started process (PID=241) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:15:42,847] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:15:42,848] {logging_mixin.py:109} INFO - [2022-04-13 06:15:42,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:15:42,851] {logging_mixin.py:109} INFO - [2022-04-13 06:15:42,850] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:15:42,873] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:15:42,883] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
[2022-04-13 06:16:12,956] {processor.py:163} INFO - Started process (PID=262) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:16:12,963] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:16:12,963] {logging_mixin.py:109} INFO - [2022-04-13 06:16:12,963] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:16:12,966] {logging_mixin.py:109} INFO - [2022-04-13 06:16:12,965] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:16:12,986] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:16:12,995] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.043 seconds
[2022-04-13 06:16:43,077] {processor.py:163} INFO - Started process (PID=294) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:16:43,079] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:16:43,080] {logging_mixin.py:109} INFO - [2022-04-13 06:16:43,080] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:16:43,083] {logging_mixin.py:109} INFO - [2022-04-13 06:16:43,082] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:16:43,107] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:16:43,118] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.046 seconds
[2022-04-13 06:17:13,175] {processor.py:163} INFO - Started process (PID=314) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:17:13,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:17:13,202] {logging_mixin.py:109} INFO - [2022-04-13 06:17:13,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:17:13,205] {logging_mixin.py:109} INFO - [2022-04-13 06:17:13,204] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:17:13,223] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:17:13,233] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.062 seconds
[2022-04-13 06:17:43,300] {processor.py:163} INFO - Started process (PID=334) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:17:43,307] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:17:43,308] {logging_mixin.py:109} INFO - [2022-04-13 06:17:43,307] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:17:43,310] {logging_mixin.py:109} INFO - [2022-04-13 06:17:43,309] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:17:43,329] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:17:43,338] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.043 seconds
[2022-04-13 06:18:13,420] {processor.py:163} INFO - Started process (PID=363) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:18:13,421] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:18:13,422] {logging_mixin.py:109} INFO - [2022-04-13 06:18:13,422] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:18:13,425] {logging_mixin.py:109} INFO - [2022-04-13 06:18:13,424] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:18:13,448] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:18:13,457] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
[2022-04-13 06:18:43,518] {processor.py:163} INFO - Started process (PID=383) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:18:43,531] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:18:43,532] {logging_mixin.py:109} INFO - [2022-04-13 06:18:43,532] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:18:43,535] {logging_mixin.py:109} INFO - [2022-04-13 06:18:43,534] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:18:43,553] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:18:43,563] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.049 seconds
[2022-04-13 06:19:13,642] {processor.py:163} INFO - Started process (PID=414) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:19:13,644] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:19:13,645] {logging_mixin.py:109} INFO - [2022-04-13 06:19:13,645] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:19:13,648] {logging_mixin.py:109} INFO - [2022-04-13 06:19:13,647] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:19:13,667] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:19:13,676] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.039 seconds
[2022-04-13 06:19:43,779] {processor.py:163} INFO - Started process (PID=435) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:19:43,804] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:19:43,805] {logging_mixin.py:109} INFO - [2022-04-13 06:19:43,805] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:19:43,808] {logging_mixin.py:109} INFO - [2022-04-13 06:19:43,807] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:19:43,826] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:19:43,836] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.061 seconds
[2022-04-13 06:20:13,893] {processor.py:163} INFO - Started process (PID=454) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:20:13,894] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:20:13,895] {logging_mixin.py:109} INFO - [2022-04-13 06:20:13,895] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:20:13,898] {logging_mixin.py:109} INFO - [2022-04-13 06:20:13,897] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:20:13,917] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:20:13,926] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.037 seconds
[2022-04-13 06:20:44,009] {processor.py:163} INFO - Started process (PID=488) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:20:44,021] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:20:44,022] {logging_mixin.py:109} INFO - [2022-04-13 06:20:44,022] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:20:44,025] {logging_mixin.py:109} INFO - [2022-04-13 06:20:44,024] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:20:44,049] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:20:44,061] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.057 seconds
[2022-04-13 06:21:14,119] {processor.py:163} INFO - Started process (PID=510) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:21:14,120] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:21:14,121] {logging_mixin.py:109} INFO - [2022-04-13 06:21:14,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:21:14,124] {logging_mixin.py:109} INFO - [2022-04-13 06:21:14,123] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:21:14,142] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:21:14,151] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.037 seconds
[2022-04-13 06:21:44,235] {processor.py:163} INFO - Started process (PID=529) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:21:44,249] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:21:44,250] {logging_mixin.py:109} INFO - [2022-04-13 06:21:44,249] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:21:44,252] {logging_mixin.py:109} INFO - [2022-04-13 06:21:44,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:21:44,272] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:21:44,281] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.050 seconds
[2022-04-13 06:22:14,351] {processor.py:163} INFO - Started process (PID=559) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:22:14,353] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:22:14,353] {logging_mixin.py:109} INFO - [2022-04-13 06:22:14,353] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:22:14,356] {logging_mixin.py:109} INFO - [2022-04-13 06:22:14,355] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:22:14,374] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:22:14,384] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.037 seconds
[2022-04-13 06:22:44,479] {processor.py:163} INFO - Started process (PID=579) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:22:44,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:22:44,490] {logging_mixin.py:109} INFO - [2022-04-13 06:22:44,490] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:22:44,493] {logging_mixin.py:109} INFO - [2022-04-13 06:22:44,492] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:22:44,513] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:22:44,522] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.048 seconds
[2022-04-13 06:23:14,587] {processor.py:163} INFO - Started process (PID=609) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:23:14,609] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:23:14,609] {logging_mixin.py:109} INFO - [2022-04-13 06:23:14,609] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:23:14,612] {logging_mixin.py:109} INFO - [2022-04-13 06:23:14,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:23:14,635] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:23:14,645] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.062 seconds
[2022-04-13 06:23:44,702] {processor.py:163} INFO - Started process (PID=629) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:23:44,703] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:23:44,704] {logging_mixin.py:109} INFO - [2022-04-13 06:23:44,704] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:23:44,707] {logging_mixin.py:109} INFO - [2022-04-13 06:23:44,706] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:23:44,725] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:23:44,735] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.037 seconds
[2022-04-13 06:24:14,812] {processor.py:163} INFO - Started process (PID=651) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:24:14,828] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:24:14,828] {logging_mixin.py:109} INFO - [2022-04-13 06:24:14,828] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:24:14,831] {logging_mixin.py:109} INFO - [2022-04-13 06:24:14,830] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:24:14,851] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:24:14,861] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.053 seconds
[2022-04-13 06:24:44,926] {processor.py:163} INFO - Started process (PID=681) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:24:44,949] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:24:44,950] {logging_mixin.py:109} INFO - [2022-04-13 06:24:44,950] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:24:44,953] {logging_mixin.py:109} INFO - [2022-04-13 06:24:44,952] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:24:44,974] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:24:44,983] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.062 seconds
[2022-04-13 06:25:15,071] {processor.py:163} INFO - Started process (PID=701) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:25:15,073] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:25:15,074] {logging_mixin.py:109} INFO - [2022-04-13 06:25:15,073] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:25:15,077] {logging_mixin.py:109} INFO - [2022-04-13 06:25:15,076] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:25:15,096] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:25:15,107] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.040 seconds
[2022-04-13 06:25:45,199] {processor.py:163} INFO - Started process (PID=722) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:25:45,212] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:25:45,213] {logging_mixin.py:109} INFO - [2022-04-13 06:25:45,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:25:45,215] {logging_mixin.py:109} INFO - [2022-04-13 06:25:45,214] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:25:45,247] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:25:45,257] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.063 seconds
[2022-04-13 06:26:15,309] {processor.py:163} INFO - Started process (PID=752) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:26:15,321] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:26:15,322] {logging_mixin.py:109} INFO - [2022-04-13 06:26:15,321] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:26:15,324] {logging_mixin.py:109} INFO - [2022-04-13 06:26:15,323] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:26:15,343] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:26:15,354] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.049 seconds
[2022-04-13 06:26:45,425] {processor.py:163} INFO - Started process (PID=774) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:26:45,426] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:26:45,427] {logging_mixin.py:109} INFO - [2022-04-13 06:26:45,427] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:26:45,430] {logging_mixin.py:109} INFO - [2022-04-13 06:26:45,429] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:26:45,449] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:26:45,457] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.036 seconds
[2022-04-13 06:27:15,532] {processor.py:163} INFO - Started process (PID=805) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:27:15,543] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:27:15,544] {logging_mixin.py:109} INFO - [2022-04-13 06:27:15,544] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:27:15,547] {logging_mixin.py:109} INFO - [2022-04-13 06:27:15,546] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:27:15,567] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:27:15,577] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.049 seconds
[2022-04-13 06:27:45,669] {processor.py:163} INFO - Started process (PID=827) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:27:45,672] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:27:45,673] {logging_mixin.py:109} INFO - [2022-04-13 06:27:45,673] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:27:45,677] {logging_mixin.py:109} INFO - [2022-04-13 06:27:45,675] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:27:45,705] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:27:45,718] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.056 seconds
[2022-04-13 06:28:15,791] {processor.py:163} INFO - Started process (PID=856) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:28:15,795] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:28:15,796] {logging_mixin.py:109} INFO - [2022-04-13 06:28:15,796] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:28:15,800] {logging_mixin.py:109} INFO - [2022-04-13 06:28:15,799] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:28:15,826] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:28:15,840] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.056 seconds
[2022-04-13 06:28:45,909] {processor.py:163} INFO - Started process (PID=875) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:28:45,911] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:28:45,912] {logging_mixin.py:109} INFO - [2022-04-13 06:28:45,912] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:28:45,917] {logging_mixin.py:109} INFO - [2022-04-13 06:28:45,916] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:28:45,937] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:28:45,947] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.044 seconds
[2022-04-13 06:29:16,043] {processor.py:163} INFO - Started process (PID=896) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:29:16,054] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:29:16,055] {logging_mixin.py:109} INFO - [2022-04-13 06:29:16,054] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:29:16,058] {logging_mixin.py:109} INFO - [2022-04-13 06:29:16,057] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:29:16,080] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:29:16,093] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.056 seconds
[2022-04-13 06:29:46,153] {processor.py:163} INFO - Started process (PID=924) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:29:46,155] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:29:46,156] {logging_mixin.py:109} INFO - [2022-04-13 06:29:46,156] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:29:46,159] {logging_mixin.py:109} INFO - [2022-04-13 06:29:46,158] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:29:46,180] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:29:46,190] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
[2022-04-13 06:30:16,273] {processor.py:163} INFO - Started process (PID=945) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:30:16,295] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:30:16,296] {logging_mixin.py:109} INFO - [2022-04-13 06:30:16,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:30:16,299] {logging_mixin.py:109} INFO - [2022-04-13 06:30:16,298] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:30:16,319] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:30:16,329] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.060 seconds
[2022-04-13 06:30:46,391] {processor.py:163} INFO - Started process (PID=967) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:30:46,394] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:30:46,395] {logging_mixin.py:109} INFO - [2022-04-13 06:30:46,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:30:46,398] {logging_mixin.py:109} INFO - [2022-04-13 06:30:46,397] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:30:46,421] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:30:46,434] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.047 seconds
[2022-04-13 06:31:16,510] {processor.py:163} INFO - Started process (PID=997) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:31:16,522] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:31:16,523] {logging_mixin.py:109} INFO - [2022-04-13 06:31:16,523] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:31:16,527] {logging_mixin.py:109} INFO - [2022-04-13 06:31:16,525] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:31:16,554] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:31:16,568] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.063 seconds
[2022-04-13 06:31:46,618] {processor.py:163} INFO - Started process (PID=1018) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:31:46,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:31:46,620] {logging_mixin.py:109} INFO - [2022-04-13 06:31:46,620] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:31:46,623] {logging_mixin.py:109} INFO - [2022-04-13 06:31:46,622] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:31:46,642] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:31:46,652] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.040 seconds
[2022-04-13 06:32:16,755] {processor.py:163} INFO - Started process (PID=1047) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:32:16,768] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:32:16,769] {logging_mixin.py:109} INFO - [2022-04-13 06:32:16,769] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:32:16,773] {logging_mixin.py:109} INFO - [2022-04-13 06:32:16,772] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:32:16,799] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:32:16,813] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.064 seconds
[2022-04-13 06:32:46,866] {processor.py:163} INFO - Started process (PID=1072) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:32:46,867] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:32:46,868] {logging_mixin.py:109} INFO - [2022-04-13 06:32:46,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:32:46,871] {logging_mixin.py:109} INFO - [2022-04-13 06:32:46,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:32:46,890] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:32:46,904] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.043 seconds
[2022-04-13 06:33:16,994] {processor.py:163} INFO - Started process (PID=1091) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:33:17,006] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:33:17,007] {logging_mixin.py:109} INFO - [2022-04-13 06:33:17,007] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:33:17,010] {logging_mixin.py:109} INFO - [2022-04-13 06:33:17,009] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:33:17,028] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:33:17,038] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.048 seconds
[2022-04-13 06:33:47,112] {processor.py:163} INFO - Started process (PID=1121) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:33:47,113] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:33:47,114] {logging_mixin.py:109} INFO - [2022-04-13 06:33:47,113] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:33:47,116] {logging_mixin.py:109} INFO - [2022-04-13 06:33:47,115] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:33:47,136] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:33:47,146] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.039 seconds
[2022-04-13 06:34:17,226] {processor.py:163} INFO - Started process (PID=1143) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:34:17,242] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:34:17,243] {logging_mixin.py:109} INFO - [2022-04-13 06:34:17,243] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:34:17,246] {logging_mixin.py:109} INFO - [2022-04-13 06:34:17,245] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:34:17,269] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:34:17,282] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.060 seconds
[2022-04-13 06:34:47,342] {processor.py:163} INFO - Started process (PID=1172) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:34:47,343] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:34:47,343] {logging_mixin.py:109} INFO - [2022-04-13 06:34:47,343] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:34:47,346] {logging_mixin.py:109} INFO - [2022-04-13 06:34:47,345] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:34:47,365] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:34:47,374] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.037 seconds
[2022-04-13 06:35:17,457] {processor.py:163} INFO - Started process (PID=1192) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:35:17,474] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:35:17,474] {logging_mixin.py:109} INFO - [2022-04-13 06:35:17,474] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:35:17,477] {logging_mixin.py:109} INFO - [2022-04-13 06:35:17,476] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:35:17,497] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:35:17,506] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.054 seconds
[2022-04-13 06:35:47,574] {processor.py:163} INFO - Started process (PID=1214) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:35:47,575] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:35:47,576] {logging_mixin.py:109} INFO - [2022-04-13 06:35:47,576] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:35:47,579] {logging_mixin.py:109} INFO - [2022-04-13 06:35:47,578] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:35:47,598] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:35:47,608] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.038 seconds
[2022-04-13 06:36:17,685] {processor.py:163} INFO - Started process (PID=1246) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:36:17,700] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:36:17,701] {logging_mixin.py:109} INFO - [2022-04-13 06:36:17,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:36:17,704] {logging_mixin.py:109} INFO - [2022-04-13 06:36:17,703] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:36:17,723] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:36:17,732] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.052 seconds
[2022-04-13 06:36:47,799] {processor.py:163} INFO - Started process (PID=1268) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:36:47,809] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:36:47,810] {logging_mixin.py:109} INFO - [2022-04-13 06:36:47,810] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:36:47,813] {logging_mixin.py:109} INFO - [2022-04-13 06:36:47,812] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:36:47,832] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:36:47,842] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.047 seconds
[2022-04-13 06:37:17,913] {processor.py:163} INFO - Started process (PID=1301) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:37:17,926] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:37:17,927] {logging_mixin.py:109} INFO - [2022-04-13 06:37:17,927] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:37:17,931] {logging_mixin.py:109} INFO - [2022-04-13 06:37:17,930] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:37:17,953] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:37:17,964] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.056 seconds
[2022-04-13 06:37:48,045] {processor.py:163} INFO - Started process (PID=1321) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:37:48,046] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:37:48,047] {logging_mixin.py:109} INFO - [2022-04-13 06:37:48,046] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:37:48,049] {logging_mixin.py:109} INFO - [2022-04-13 06:37:48,048] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:37:48,069] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:37:48,078] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.038 seconds
[2022-04-13 06:38:18,162] {processor.py:163} INFO - Started process (PID=1342) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:38:18,185] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:38:18,186] {logging_mixin.py:109} INFO - [2022-04-13 06:38:18,186] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:38:18,189] {logging_mixin.py:109} INFO - [2022-04-13 06:38:18,188] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:38:18,209] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:38:18,219] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.061 seconds
[2022-04-13 06:38:48,272] {processor.py:163} INFO - Started process (PID=1374) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:38:48,287] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:38:48,288] {logging_mixin.py:109} INFO - [2022-04-13 06:38:48,288] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:38:48,291] {logging_mixin.py:109} INFO - [2022-04-13 06:38:48,290] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:38:48,312] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:38:48,322] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.055 seconds
[2022-04-13 06:39:18,394] {processor.py:163} INFO - Started process (PID=1397) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:39:18,395] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:39:18,396] {logging_mixin.py:109} INFO - [2022-04-13 06:39:18,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:39:18,399] {logging_mixin.py:109} INFO - [2022-04-13 06:39:18,398] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:39:18,420] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:39:18,432] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.044 seconds
[2022-04-13 06:39:48,514] {processor.py:163} INFO - Started process (PID=1428) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:39:48,535] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:39:48,536] {logging_mixin.py:109} INFO - [2022-04-13 06:39:48,536] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:39:48,541] {logging_mixin.py:109} INFO - [2022-04-13 06:39:48,539] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:39:48,571] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:39:48,589] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.081 seconds
[2022-04-13 06:40:18,623] {processor.py:163} INFO - Started process (PID=1449) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:40:18,626] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:40:18,628] {logging_mixin.py:109} INFO - [2022-04-13 06:40:18,628] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:40:18,631] {logging_mixin.py:109} INFO - [2022-04-13 06:40:18,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:40:18,654] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:40:18,671] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.053 seconds
[2022-04-13 06:40:48,809] {processor.py:163} INFO - Started process (PID=1471) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:40:48,829] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:40:48,831] {logging_mixin.py:109} INFO - [2022-04-13 06:40:48,830] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:40:48,835] {logging_mixin.py:109} INFO - [2022-04-13 06:40:48,834] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:40:48,857] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:40:48,869] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.066 seconds
[2022-04-13 06:41:18,931] {processor.py:163} INFO - Started process (PID=1492) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:41:18,934] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:41:18,935] {logging_mixin.py:109} INFO - [2022-04-13 06:41:18,935] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:41:18,938] {logging_mixin.py:109} INFO - [2022-04-13 06:41:18,937] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:41:18,961] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:41:18,974] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.049 seconds
[2022-04-13 06:41:49,070] {processor.py:163} INFO - Started process (PID=1522) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:41:49,072] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:41:49,073] {logging_mixin.py:109} INFO - [2022-04-13 06:41:49,073] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:41:49,078] {logging_mixin.py:109} INFO - [2022-04-13 06:41:49,076] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:41:49,108] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:41:49,122] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.058 seconds
[2022-04-13 06:42:19,179] {processor.py:163} INFO - Started process (PID=1542) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:42:19,191] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:42:19,192] {logging_mixin.py:109} INFO - [2022-04-13 06:42:19,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:42:19,195] {logging_mixin.py:109} INFO - [2022-04-13 06:42:19,194] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:42:19,218] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:42:19,231] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.057 seconds
[2022-04-13 06:42:49,351] {processor.py:163} INFO - Started process (PID=1563) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:42:49,352] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:42:49,353] {logging_mixin.py:109} INFO - [2022-04-13 06:42:49,353] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:42:49,356] {logging_mixin.py:109} INFO - [2022-04-13 06:42:49,355] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:42:49,378] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:42:49,389] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.043 seconds
[2022-04-13 06:43:19,463] {processor.py:163} INFO - Started process (PID=1594) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:43:19,487] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:43:19,488] {logging_mixin.py:109} INFO - [2022-04-13 06:43:19,488] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:43:19,491] {logging_mixin.py:109} INFO - [2022-04-13 06:43:19,490] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:43:19,511] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:43:19,521] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.062 seconds
[2022-04-13 06:43:49,584] {processor.py:163} INFO - Started process (PID=1615) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:43:49,586] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:43:49,587] {logging_mixin.py:109} INFO - [2022-04-13 06:43:49,587] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:43:49,592] {logging_mixin.py:109} INFO - [2022-04-13 06:43:49,590] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:43:49,620] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:43:49,634] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.056 seconds
[2022-04-13 06:44:19,708] {processor.py:163} INFO - Started process (PID=1645) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:44:19,722] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:44:19,723] {logging_mixin.py:109} INFO - [2022-04-13 06:44:19,723] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:44:19,727] {logging_mixin.py:109} INFO - [2022-04-13 06:44:19,726] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:44:19,755] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:44:19,771] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.069 seconds
[2022-04-13 06:44:49,819] {processor.py:163} INFO - Started process (PID=1666) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:44:49,821] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:44:49,822] {logging_mixin.py:109} INFO - [2022-04-13 06:44:49,821] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:44:49,825] {logging_mixin.py:109} INFO - [2022-04-13 06:44:49,824] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:44:49,848] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:44:49,860] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.045 seconds
[2022-04-13 06:45:19,957] {processor.py:163} INFO - Started process (PID=1687) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:45:19,970] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:45:19,971] {logging_mixin.py:109} INFO - [2022-04-13 06:45:19,971] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:45:19,975] {logging_mixin.py:109} INFO - [2022-04-13 06:45:19,974] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:45:19,996] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:45:20,007] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.055 seconds
[2022-04-13 06:45:50,071] {processor.py:163} INFO - Started process (PID=1719) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:45:50,087] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:45:50,088] {logging_mixin.py:109} INFO - [2022-04-13 06:45:50,087] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:45:50,091] {logging_mixin.py:109} INFO - [2022-04-13 06:45:50,090] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:45:50,114] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:45:50,126] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.059 seconds
[2022-04-13 06:46:20,195] {processor.py:163} INFO - Started process (PID=1740) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:46:20,196] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:46:20,197] {logging_mixin.py:109} INFO - [2022-04-13 06:46:20,197] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:46:20,200] {logging_mixin.py:109} INFO - [2022-04-13 06:46:20,199] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:46:20,218] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:46:20,227] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.036 seconds
[2022-04-13 06:46:50,306] {processor.py:163} INFO - Started process (PID=1762) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:46:50,363] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:46:50,365] {logging_mixin.py:109} INFO - [2022-04-13 06:46:50,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:46:50,370] {logging_mixin.py:109} INFO - [2022-04-13 06:46:50,369] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:46:50,394] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:46:50,406] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.104 seconds
[2022-04-13 06:47:20,482] {processor.py:163} INFO - Started process (PID=1792) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:47:20,484] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:47:20,485] {logging_mixin.py:109} INFO - [2022-04-13 06:47:20,485] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:47:20,488] {logging_mixin.py:109} INFO - [2022-04-13 06:47:20,487] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:47:20,508] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:47:20,518] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.041 seconds
[2022-04-13 06:47:50,598] {processor.py:163} INFO - Started process (PID=1812) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:47:50,609] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:47:50,610] {logging_mixin.py:109} INFO - [2022-04-13 06:47:50,609] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:47:50,612] {logging_mixin.py:109} INFO - [2022-04-13 06:47:50,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:47:50,631] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:47:50,774] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.180 seconds
[2022-04-13 06:48:20,845] {processor.py:163} INFO - Started process (PID=1844) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:48:20,855] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:48:20,856] {logging_mixin.py:109} INFO - [2022-04-13 06:48:20,856] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:48:20,861] {logging_mixin.py:109} INFO - [2022-04-13 06:48:20,859] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:48:21,030] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:48:21,040] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.200 seconds
[2022-04-13 06:48:51,113] {processor.py:163} INFO - Started process (PID=1863) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:48:51,115] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:48:51,116] {logging_mixin.py:109} INFO - [2022-04-13 06:48:51,116] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:48:51,119] {logging_mixin.py:109} INFO - [2022-04-13 06:48:51,118] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:48:51,138] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:48:51,148] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.040 seconds
[2022-04-13 06:49:21,220] {processor.py:163} INFO - Started process (PID=1895) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:49:21,230] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:49:21,231] {logging_mixin.py:109} INFO - [2022-04-13 06:49:21,230] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:49:21,234] {logging_mixin.py:109} INFO - [2022-04-13 06:49:21,233] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:49:21,256] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:49:21,270] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.055 seconds
[2022-04-13 06:49:51,336] {processor.py:163} INFO - Started process (PID=1916) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:49:51,337] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:49:51,338] {logging_mixin.py:109} INFO - [2022-04-13 06:49:51,338] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:49:51,341] {logging_mixin.py:109} INFO - [2022-04-13 06:49:51,340] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:49:51,360] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:49:51,369] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.037 seconds
[2022-04-13 06:50:21,453] {processor.py:163} INFO - Started process (PID=1937) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:50:21,468] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:50:21,469] {logging_mixin.py:109} INFO - [2022-04-13 06:50:21,469] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:50:21,473] {logging_mixin.py:109} INFO - [2022-04-13 06:50:21,471] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:50:21,493] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:50:21,503] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.054 seconds
[2022-04-13 06:50:51,561] {processor.py:163} INFO - Started process (PID=1968) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:50:51,562] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:50:51,563] {logging_mixin.py:109} INFO - [2022-04-13 06:50:51,563] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:50:51,566] {logging_mixin.py:109} INFO - [2022-04-13 06:50:51,565] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:50:51,584] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:50:51,595] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.038 seconds
[2022-04-13 06:51:21,676] {processor.py:163} INFO - Started process (PID=1990) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:51:21,687] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:51:21,688] {logging_mixin.py:109} INFO - [2022-04-13 06:51:21,688] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:51:21,691] {logging_mixin.py:109} INFO - [2022-04-13 06:51:21,690] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:51:21,713] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:51:21,728] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.056 seconds
[2022-04-13 06:51:51,790] {processor.py:163} INFO - Started process (PID=2018) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:51:51,804] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:51:51,805] {logging_mixin.py:109} INFO - [2022-04-13 06:51:51,805] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:51:51,808] {logging_mixin.py:109} INFO - [2022-04-13 06:51:51,807] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:51:51,827] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:51:51,836] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.050 seconds
[2022-04-13 06:52:21,908] {processor.py:163} INFO - Started process (PID=2037) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:52:21,909] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:52:21,910] {logging_mixin.py:109} INFO - [2022-04-13 06:52:21,910] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:52:21,913] {logging_mixin.py:109} INFO - [2022-04-13 06:52:21,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:52:21,934] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:52:21,943] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.040 seconds
[2022-04-13 06:52:52,031] {processor.py:163} INFO - Started process (PID=2068) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:52:52,048] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:52:52,049] {logging_mixin.py:109} INFO - [2022-04-13 06:52:52,049] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:52:52,052] {logging_mixin.py:109} INFO - [2022-04-13 06:52:52,051] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:52:52,076] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:52:52,088] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.062 seconds
[2022-04-13 06:53:22,149] {processor.py:163} INFO - Started process (PID=2088) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:53:22,150] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:53:22,151] {logging_mixin.py:109} INFO - [2022-04-13 06:53:22,150] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:53:22,153] {logging_mixin.py:109} INFO - [2022-04-13 06:53:22,152] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:53:22,172] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:53:22,183] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.039 seconds
[2022-04-13 06:53:52,306] {processor.py:163} INFO - Started process (PID=2109) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:53:52,341] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:53:52,342] {logging_mixin.py:109} INFO - [2022-04-13 06:53:52,342] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:53:52,345] {logging_mixin.py:109} INFO - [2022-04-13 06:53:52,344] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:53:52,382] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:53:52,411] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.109 seconds
[2022-04-13 06:54:22,491] {processor.py:163} INFO - Started process (PID=2140) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:54:22,519] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:54:22,520] {logging_mixin.py:109} INFO - [2022-04-13 06:54:22,519] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:54:22,525] {logging_mixin.py:109} INFO - [2022-04-13 06:54:22,523] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:54:22,551] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:54:22,564] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.079 seconds
[2022-04-13 06:54:52,606] {processor.py:163} INFO - Started process (PID=2168) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:54:52,607] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:54:52,608] {logging_mixin.py:109} INFO - [2022-04-13 06:54:52,608] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:54:52,611] {logging_mixin.py:109} INFO - [2022-04-13 06:54:52,610] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:54:52,630] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:54:52,639] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.038 seconds
[2022-04-13 06:55:22,748] {processor.py:163} INFO - Started process (PID=2188) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:55:22,766] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:55:22,767] {logging_mixin.py:109} INFO - [2022-04-13 06:55:22,767] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:55:22,771] {logging_mixin.py:109} INFO - [2022-04-13 06:55:22,770] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:55:22,802] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:55:22,812] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.069 seconds
[2022-04-13 06:55:52,857] {processor.py:163} INFO - Started process (PID=2219) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:55:52,858] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:55:52,859] {logging_mixin.py:109} INFO - [2022-04-13 06:55:52,859] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:55:52,862] {logging_mixin.py:109} INFO - [2022-04-13 06:55:52,861] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:55:52,884] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:55:52,894] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
[2022-04-13 06:56:22,985] {processor.py:163} INFO - Started process (PID=2240) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:56:23,016] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:56:23,017] {logging_mixin.py:109} INFO - [2022-04-13 06:56:23,016] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:56:23,020] {logging_mixin.py:109} INFO - [2022-04-13 06:56:23,019] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:56:23,039] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:56:23,049] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.068 seconds
[2022-04-13 06:56:53,133] {processor.py:163} INFO - Started process (PID=2269) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:56:53,136] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:56:53,138] {logging_mixin.py:109} INFO - [2022-04-13 06:56:53,138] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:56:53,144] {logging_mixin.py:109} INFO - [2022-04-13 06:56:53,142] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:56:53,181] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:56:53,197] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.079 seconds
[2022-04-13 06:57:23,235] {processor.py:163} INFO - Started process (PID=2291) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:57:23,249] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:57:23,249] {logging_mixin.py:109} INFO - [2022-04-13 06:57:23,249] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:57:23,252] {logging_mixin.py:109} INFO - [2022-04-13 06:57:23,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:57:23,270] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:57:23,280] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.049 seconds
[2022-04-13 06:57:53,418] {processor.py:163} INFO - Started process (PID=2312) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:57:53,430] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:57:53,431] {logging_mixin.py:109} INFO - [2022-04-13 06:57:53,431] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:57:53,434] {logging_mixin.py:109} INFO - [2022-04-13 06:57:53,433] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:57:53,453] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:57:53,462] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.048 seconds
[2022-04-13 06:58:23,539] {processor.py:163} INFO - Started process (PID=2344) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:58:23,540] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:58:23,541] {logging_mixin.py:109} INFO - [2022-04-13 06:58:23,541] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:58:23,545] {logging_mixin.py:109} INFO - [2022-04-13 06:58:23,544] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:58:23,568] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:58:23,581] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.047 seconds
[2022-04-13 06:58:53,638] {processor.py:163} INFO - Started process (PID=2364) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:58:53,651] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:58:53,652] {logging_mixin.py:109} INFO - [2022-04-13 06:58:53,652] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:58:53,655] {logging_mixin.py:109} INFO - [2022-04-13 06:58:53,654] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:58:53,674] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:58:53,684] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.050 seconds
[2022-04-13 06:59:23,757] {processor.py:163} INFO - Started process (PID=2385) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:59:23,763] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:59:23,764] {logging_mixin.py:109} INFO - [2022-04-13 06:59:23,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:59:23,766] {logging_mixin.py:109} INFO - [2022-04-13 06:59:23,766] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:59:23,786] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:59:23,795] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
[2022-04-13 06:59:53,876] {processor.py:163} INFO - Started process (PID=2415) to work on /opt/airflow/dags/transform.py
[2022-04-13 06:59:53,877] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 06:59:53,878] {logging_mixin.py:109} INFO - [2022-04-13 06:59:53,878] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 06:59:53,881] {logging_mixin.py:109} INFO - [2022-04-13 06:59:53,880] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 06:59:53,900] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 06:59:53,909] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.038 seconds
[2022-04-13 07:00:23,984] {processor.py:163} INFO - Started process (PID=2433) to work on /opt/airflow/dags/transform.py
[2022-04-13 07:00:23,995] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 07:00:23,995] {logging_mixin.py:109} INFO - [2022-04-13 07:00:23,995] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 07:00:23,998] {logging_mixin.py:109} INFO - [2022-04-13 07:00:23,997] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 07:00:24,018] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 07:00:24,030] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.051 seconds
[2022-04-13 07:00:54,102] {processor.py:163} INFO - Started process (PID=2465) to work on /opt/airflow/dags/transform.py
[2022-04-13 07:00:54,105] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 07:00:54,106] {logging_mixin.py:109} INFO - [2022-04-13 07:00:54,106] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 07:00:54,109] {logging_mixin.py:109} INFO - [2022-04-13 07:00:54,108] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 07:00:54,131] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 07:00:54,142] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.044 seconds
[2022-04-13 07:01:24,218] {processor.py:163} INFO - Started process (PID=2486) to work on /opt/airflow/dags/transform.py
[2022-04-13 07:01:24,219] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 07:01:24,220] {logging_mixin.py:109} INFO - [2022-04-13 07:01:24,219] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 07:01:24,222] {logging_mixin.py:109} INFO - [2022-04-13 07:01:24,222] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 07:01:24,242] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 07:01:24,253] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.040 seconds
[2022-04-13 07:01:54,337] {processor.py:163} INFO - Started process (PID=2518) to work on /opt/airflow/dags/transform.py
[2022-04-13 07:01:54,356] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 07:01:54,357] {logging_mixin.py:109} INFO - [2022-04-13 07:01:54,357] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 07:01:54,362] {logging_mixin.py:109} INFO - [2022-04-13 07:01:54,360] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 07:01:54,389] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 07:01:54,403] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.071 seconds
[2022-04-13 07:02:24,448] {processor.py:163} INFO - Started process (PID=2539) to work on /opt/airflow/dags/transform.py
[2022-04-13 07:02:24,450] {processor.py:642} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2022-04-13 07:02:24,450] {logging_mixin.py:109} INFO - [2022-04-13 07:02:24,450] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2022-04-13 07:02:24,453] {logging_mixin.py:109} INFO - [2022-04-13 07:02:24,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 95
    delete_external_table_task >>
                                 ^
SyntaxError: invalid syntax
[2022-04-13 07:02:24,473] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2022-04-13 07:02:24,483] {processor.py:171} INFO - Processing /opt/airflow/dags/transform.py took 0.039 seconds
